package e

//类别
var BingCategory = []string{"front-end-development", "mobile-development", "data-mining", "machine-learning", "big-data-and-cloud-computing", "back-end-development", "search-engine", "fundamentals-of-compiling", "hardware", "operating-system", "blockchain", "message-queue", "game-development-and-design", "internet-and-science", "network-programming", "algorithm-and-data-structure", "ops", "cyber-security", "interactive-design", "software-development-and-engineering", "database", "computer-science", "uncategorized"}
var SmallCategory = []string{"c++", "go", "python", "other", "java", "c", "php", "c%23", "rust", "erlang", "ios", "android", "javascript", "framework-and-library", "node-js", "html-and-css", ""}

//类别名称对应关系
var Mapper = map[string]string{"back-end-development": "后端开发",
	"front-end-development":                "前端开发",
	"mobile-development":                   "移动开发",
	"machine-learning":                     "机器学习",
	"ops":                                  "运维管理",
	"cyber-security":                       "网络安全",
	"fundamentals-of-compiling":            "编译原理",
	"search-engine":                        "搜索引擎",
	"big-data-and-cloud-computing":         "大数据与云计算",
	"data-mining":                          "数据挖掘",
	"network-programming":                  "网络编程",
	"blockchain":                           "区块链",
	"interactive-design":                   "交互设计",
	"internet-and-science":                 "计算机科学",
	"game-development-and-design":          "游戏开发与游戏设计",
	"hardware":                             "硬件",
	"uncategorized":                        "其他",
	"software-development-and-engineering": "软件开发与软件工程",
	"algorithm-and-data-structure":         "算法与数据结构",
	"message-queue":                        "消息队列",
	"operating-system":                     "操作系统",
	"computer-science":                     "计算机科学",
	"database":                             "数据库",
	"c++":                                  "C++",
	"go":                                   "Go",
	"python":                               "Python",
	"other":                                "其他",
	"java":                                 "Java",
	"c":                                    "C",
	"php":                                  "PHP",
	"rust":                                 "Rust",
	"erlang":                               "Erlang",
	"c%23":                                 "C#",
	"javascript":                           "JavaScript",
	"framework-and-library":                "框架和库",
	"node-js":                              "Node.js",
	"html-and-css":                         "HTML&CSS",
	"ios":                                  "IOS",
	"android":                              "Andriod",
}
